import express from "express";
import { bundle } from "@remotion/bundler";
import { getCompositions, renderMedia, selectComposition } from "@remotion/renderer";
import { GetObjectCommand, PutObjectCommand, S3Client } from "@aws-sdk/client-s3";
import { createReadStream, createWriteStream } from "node:fs";
import { access, copyFile, mkdtemp, mkdir, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { randomUUID } from "node:crypto";
import { Readable } from "node:stream";
import { pipeline } from "node:stream/promises";
import type { ReadableStream as NodeReadableStream } from "node:stream/web";
import { execFile, spawn } from "node:child_process";
import { promisify } from "node:util";
import { REMOTION_COMPOSITION_ID, REMOTION_SHORT_COMPOSITION_ID } from "./constants.js";
import { type SceneProps, type SegmentMetadata } from "./segmentTiming.js";

const PORT = Number(process.env.PORT ?? 3000);
const DEFAULT_PREFIX = "remotion";
const bucketName =
  process.env.PAPERCLIP_STORAGE_S3_BUCKET ?? process.env.REMOTION_STORAGE_S3_BUCKET;
const localOutputDir = process.env.REMOTION_LOCAL_OUTPUT_DIR;

const region =
  process.env.PAPERCLIP_STORAGE_S3_REGION ??
  process.env.REMOTION_STORAGE_S3_REGION ??
  "us-east-1";
const endpoint =
  process.env.PAPERCLIP_STORAGE_S3_ENDPOINT ??
  process.env.REMOTION_STORAGE_S3_ENDPOINT;
const publicOutputBaseUrl = (
  process.env.PAPERCLIP_STORAGE_PUBLIC_BASE_URL ??
  process.env.REMOTION_STORAGE_PUBLIC_BASE_URL ??
  ""
).replace(/\/+$/, "");
const servicePublicBaseUrl = (
  process.env.REMOTION_SERVICE_PUBLIC_URL ??
  process.env.PUBLIC_URL ??
  ""
).replace(/\/+$/, "");
const forcePathStyle =
  (process.env.PAPERCLIP_STORAGE_S3_FORCE_PATH_STYLE ??
    process.env.REMOTION_STORAGE_S3_FORCE_PATH_STYLE ??
    "false") === "true";
const prefix =
  (process.env.PAPERCLIP_STORAGE_S3_PREFIX ??
    process.env.REMOTION_STORAGE_S3_PREFIX ??
    DEFAULT_PREFIX)
    .replace(/^\/+/, "")
    .replace(/\/+$/, "")
    .trim();

if (!bucketName && !localOutputDir) {
  throw new Error(
    "No output configured. Set either PAPERCLIP_STORAGE_S3_BUCKET/REMOTION_STORAGE_S3_BUCKET (for S3) or REMOTION_LOCAL_OUTPUT_DIR (for local development).",
  );
}

const s3Client = bucketName
  ? new S3Client({
      region,
      endpoint,
      forcePathStyle,
    })
  : null;
const execFileAsync = promisify(execFile);
const localAssetRegistry = new Map<string, { filePath: string; contentType: string }>();
const WAVEFORM_BAR_COUNT = 72;
const AUDIO_DURATION_TAIL_PADDING_MS = 200;

const compositionSchemas = {
  [REMOTION_COMPOSITION_ID]: {
    composition: REMOTION_COMPOSITION_ID,
    endpoint: "/render or /render-async",
    requestShape: {
      composition: REMOTION_COMPOSITION_ID,
      outputKey: "optional/path-or-filename.mp4",
      props: {
        title: "optional display title",
        accent: "optional CSS color, for example #F59E0B",
        segments: [
          {
            speaker: "optional speaker label",
            url: "required http(s) audio URL",
            durationMs: "required positive number; service verifies actual audio duration",
            color: "optional CSS color",
          },
        ],
      },
    },
    required: ["props.segments[0].url", "props.segments[0].durationMs"],
    notes: [
      "`props.segments` must be a non-empty array.",
      "`waveform` is generated by the service and should not be supplied by callers.",
      "The service downloads each segment, verifies it has audio, and uses measured duration for render timing.",
    ],
  },
  [REMOTION_SHORT_COMPOSITION_ID]: {
    composition: REMOTION_SHORT_COMPOSITION_ID,
    endpoint: "/render-clips or /render-clips-async",
    requestShape: {
      video: "required http(s), file path, or local asset path unless videoKey is supplied",
      videoKey: "required S3 key unless video is supplied",
      brandId: "optional brand config id",
      authorHandle: "optional, defaults to @0xjustice",
      avatarUrl: "optional http(s) URL or local asset path",
      clips: [
        {
          id: "required stable clip id",
          title: "required title",
          start: "required start seconds",
          end: "required end seconds",
          captions: [
            {
              start: "seconds relative to clip start",
              end: "seconds relative to clip start",
              text: "caption text",
            },
          ],
        },
      ],
    },
    required: ["video or videoKey", "clips[0].id", "clips[0].title", "clips[0].start", "clips[0].end"],
  },
} as const;

const app = express();
app.disable("x-powered-by");
app.use(express.json({ limit: "1mb" }));

app.use((req, _res, next) => {
  const body = req.body as Record<string, unknown> | undefined;
  const props = body?.props as Record<string, unknown> | undefined;
  console.log("Incoming request", {
    method: req.method,
    path: req.path,
    composition: body?.composition,
    outputKey: body?.outputKey,
    title: props?.title,
    segmentCount: Array.isArray(props?.segments) ? props.segments.length : undefined,
  });
  next();
});

// In-memory job tracking for long-running clip renders started via
// /render-clips-async. This keeps the external HTTP request short
// (Railway-friendly) while the actual render work happens in the
// background by calling the existing synchronous /render-clips
// endpoint from inside the same process.

type ClipRenderJobStatus = "pending" | "running" | "completed" | "failed";

type ClipRenderJobResult = {
  video?: string;
  clips: Array<{
    id: string;
    bucket: string | null;
    key: string;
    endpoint?: string | undefined;
    location: string;
    url?: string | undefined;
    proxyUrl?: string | undefined;
  }>;
};

type ClipRenderJobRecord = {
  id: string;
  status: ClipRenderJobStatus;
  createdAt: string;
  updatedAt: string;
  error?: string;
  inputSummary: {
    video?: string;
    videoKey?: string;
    clipCount: number;
  };
  result?: ClipRenderJobResult;
};

const clipRenderJobs = new Map<string, ClipRenderJobRecord>();

function createClipRenderJob(body: Partial<ClipManifest>): ClipRenderJobRecord {
  const id = randomUUID();
  const now = new Date().toISOString();
  const clipCount = Array.isArray(body.clips) ? body.clips.length : 0;

  const job: ClipRenderJobRecord = {
    id,
    status: "pending",
    createdAt: now,
    updatedAt: now,
    inputSummary: {
      video: typeof body.video === "string" ? body.video : undefined,
      videoKey: typeof body.videoKey === "string" ? body.videoKey : undefined,
      clipCount,
    },
  };

  clipRenderJobs.set(id, job);
  return job;
}

async function runClipRenderJob(jobId: string, body: Partial<ClipManifest>): Promise<void> {
  const job = clipRenderJobs.get(jobId);
  if (!job) return;

  job.status = "running";
  job.updatedAt = new Date().toISOString();
  clipRenderJobs.set(jobId, job);

  try {
    const response = await fetch(`http://127.0.0.1:${PORT}/render-clips`, {
      method: "POST",
      headers: {
        "content-type": "application/json",
        accept: "application/json",
      },
      body: JSON.stringify(body ?? {}),
    });

    const text = await response.text();
    if (!response.ok) {
      job.status = "failed";
      job.error = `HTTP ${response.status}: ${text}`;
    } else {
      const parsed = JSON.parse(text) as ClipRenderJobResult;
      job.status = "completed";
      job.result = parsed;
    }
  } catch (error) {
    job.status = "failed";
    job.error = (error as Error)?.message ?? "Unknown render job error";
  } finally {
    job.updatedAt = new Date().toISOString();
    clipRenderJobs.set(jobId, job);
  }
}

  // In-memory job tracking for long-form /render jobs. Mirrors the
  // clip job model but for a single scene render.

  type RenderJobStatus = "pending" | "running" | "completed" | "failed";

  type RenderJobResult = {
    bucket: string | null;
    key: string;
    endpoint?: string | undefined;
    location: string;
    url?: string | undefined;
    proxyUrl?: string | undefined;
  };

  type RenderJobRecord = {
    id: string;
    status: RenderJobStatus;
    createdAt: string;
    updatedAt: string;
    error?: string;
    inputSummary: {
      composition: string;
      hasSegments: boolean;
    };
    result?: RenderJobResult;
  };

  const renderJobs = new Map<string, RenderJobRecord>();

  function createRenderJob(body: unknown): RenderJobRecord {
    const raw = (body ?? {}) as { composition?: unknown; props?: unknown };
    const composition = String(raw.composition ?? REMOTION_COMPOSITION_ID);
    const props = (raw.props ?? {}) as Record<string, unknown>;
    const hasSegments = Array.isArray((props as { segments?: unknown }).segments);

    const id = randomUUID();
    const now = new Date().toISOString();

    const job: RenderJobRecord = {
      id,
      status: "pending",
      createdAt: now,
      updatedAt: now,
      inputSummary: {
        composition,
        hasSegments,
      },
    };

    renderJobs.set(id, job);
    return job;
  }

  async function runRenderJob(jobId: string, body: unknown): Promise<void> {
    const job = renderJobs.get(jobId);
    if (!job) return;

    job.status = "running";
    job.updatedAt = new Date().toISOString();
    renderJobs.set(jobId, job);

    try {
      const result = await renderScene(body);
      job.status = "completed";
      job.result = result;
    } catch (error) {
      job.status = "failed";
      job.error = (error as Error)?.message ?? "Unknown render job error";
    } finally {
      job.updatedAt = new Date().toISOString();
      renderJobs.set(jobId, job);
    }
  }

type BundleResult = Awaited<ReturnType<typeof bundle>>;

let bundleCache: BundleResult | null = null;
let bundlePromise: Promise<BundleResult> | null = null;

const bundleEntry = path.resolve("src/index.ts");

async function ensureBundle(): Promise<BundleResult> {
  if (bundleCache) return bundleCache;
  if (!bundlePromise) {
    bundlePromise = bundle({
      entryPoint: bundleEntry,
    }).catch((err) => {
      bundlePromise = null;
      throw err;
    });
  }
  const bundleResult = await bundlePromise;
  bundleCache = bundleResult;
  return bundleResult;
}

function buildObjectKey(value: string): string {
  const sanitized = value.replace(/^\/+/, "").replace(/\/+$/, "");
  if (!prefix) return sanitized;
  return `${prefix}/${sanitized}`;
}

function ensureMp4(fileName: string): string {
  if (fileName.toLowerCase().endsWith(".mp4")) return fileName;
  return `${fileName}.mp4`;
}

function composeKey(suggested?: string, compositionId?: string): string {
  const base =
    (suggested && suggested.trim()) ||
    `${(compositionId ?? "remotion").replace(/[^a-z0-9-_]/gi, "-")}-${Date.now()}`;
  return buildObjectKey(ensureMp4(base));
}

function encodeKeyPath(key: string): string {
  return key
    .split("/")
    .filter((part) => part.length > 0)
    .map((part) => encodeURIComponent(part))
    .join("/");
}

function buildPublicOutputUrl(key: string): string | undefined {
  if (!publicOutputBaseUrl) return undefined;
  return `${publicOutputBaseUrl}/${encodeKeyPath(key)}`;
}

function buildProxyOutputUrl(key: string): string {
  const proxyPath = `/render-outputs/${encodeKeyPath(key)}`;
  return servicePublicBaseUrl ? `${servicePublicBaseUrl}${proxyPath}` : proxyPath;
}

async function uploadToS3(localPath: string, key: string): Promise<{
  bucket: string | null;
  key: string;
  location: string;
  url?: string | undefined;
  proxyUrl: string;
}> {
  if (!bucketName) {
    if (!localOutputDir) {
      throw new Error(
        "Local output requested but REMOTION_LOCAL_OUTPUT_DIR is not set. This should not happen.",
      );
    }

    const baseDir = localOutputDir.replace(/\/+$/, "");
    const destination = path.join(baseDir, key);
    await mkdir(path.dirname(destination), { recursive: true });
    await copyFile(localPath, destination);

    return {
      bucket: null,
      key,
      location: destination,
      url: undefined,
      proxyUrl: buildProxyOutputUrl(key),
    };
  }

  const stream = createReadStream(localPath);
  await s3Client!.send(
    new PutObjectCommand({
      Bucket: bucketName,
      Key: key,
      Body: stream,
      ContentType: "video/mp4",
    }),
  );

  return {
    bucket: bucketName,
    key,
    location: key,
    url: buildPublicOutputUrl(key),
    proxyUrl: buildProxyOutputUrl(key),
  };
}

function isAllowedOutputKey(key: string): boolean {
  if (key.includes("..")) return false;
  if (!prefix) return true;
  return key === prefix || key.startsWith(`${prefix}/`);
}

async function cleanupRenderArtifacts(options: {
  cleanupLocalizedSegments: (() => Promise<void>) | null;
  tmpFile: string;
}): Promise<void> {
  const { cleanupLocalizedSegments, tmpFile } = options;
  if (cleanupLocalizedSegments) {
    await cleanupLocalizedSegments();
  }

  await rm(tmpFile, { force: true });
}

function getAssetExtension(url: string, contentType: string | null): string {
  const pathname = new URL(url).pathname;
  const ext = path.extname(pathname);
  if (ext) return ext;

  if (contentType?.includes("mpeg")) return ".mp3";
  if (contentType?.includes("wav")) return ".wav";
  if (contentType?.includes("mp4")) return ".m4a";
  if (contentType?.includes("aac")) return ".aac";
  if (contentType?.includes("ogg")) return ".ogg";
  return ".bin";
}

async function probeAudio(filePath: string): Promise<void> {
  const { stdout } = await execFileAsync("ffprobe", [
    "-v",
    "error",
    "-show_streams",
    "-select_streams",
    "a:0",
    filePath,
  ]);

  if (!stdout.includes("[STREAM]")) {
    throw new Error(`Downloaded asset does not contain an audio stream: ${filePath}`);
  }
}

async function probeAudioDurationMs(filePath: string): Promise<number> {
  const { stdout } = await execFileAsync("ffprobe", [
    "-v",
    "error",
    "-show_entries",
    "format=duration",
    "-of",
    "default=noprint_wrappers=1:nokey=1",
    filePath,
  ]);
  const durationSeconds = Number(stdout.trim());

  if (!Number.isFinite(durationSeconds) || durationSeconds <= 0) {
    throw new Error(`Unable to determine audio duration for downloaded asset: ${filePath}`);
  }

  return Math.ceil(durationSeconds * 1000);
}

function allocateWaveformBars(durationsMs: number[], totalBars: number): number[] {
  if (durationsMs.length === 0) {
    return [];
  }

  const totalDurationMs = durationsMs.reduce((sum, duration) => sum + duration, 0);
  if (totalDurationMs <= 0) {
    return durationsMs.map((_duration, index) => (index === 0 ? totalBars : 0));
  }

  const allocations = durationsMs.map((duration) => (duration / totalDurationMs) * totalBars);
  const base = allocations.map((value) => Math.floor(value));
  let assigned = base.reduce((sum, value) => sum + value, 0);

  if (durationsMs.length <= totalBars) {
    for (let index = 0; index < base.length; index += 1) {
      if (base[index] === 0) {
        base[index] = 1;
        assigned += 1;
      }
    }
  }

  while (assigned > totalBars) {
    const candidate = base.findIndex((value) => value > 1);
    if (candidate === -1) {
      break;
    }
    base[candidate] -= 1;
    assigned -= 1;
  }

  const remainderOrder = allocations
    .map((value, index) => ({
      index,
      remainder: value - Math.floor(value),
    }))
    .sort((left, right) => right.remainder - left.remainder);

  let cursor = 0;
  while (assigned < totalBars && remainderOrder.length > 0) {
    base[remainderOrder[cursor % remainderOrder.length].index] += 1;
    assigned += 1;
    cursor += 1;
  }

  return base;
}

async function extractWaveformSamples(filePath: string, sampleCount: number): Promise<number[]> {
  if (sampleCount <= 0) {
    return [];
  }

  const pcm = await new Promise<Buffer>((resolve, reject) => {
    const ffmpeg = spawn("ffmpeg", [
      "-v",
      "error",
      "-i",
      filePath,
      "-ac",
      "1",
      "-ar",
      "1200",
      "-f",
      "f32le",
      "pipe:1",
    ]);

    const chunks: Buffer[] = [];
    const stderr: Buffer[] = [];

    ffmpeg.stdout.on("data", (chunk: Buffer) => {
      chunks.push(chunk);
    });

    ffmpeg.stderr.on("data", (chunk: Buffer) => {
      stderr.push(chunk);
    });

    ffmpeg.on("error", reject);
    ffmpeg.on("close", (code) => {
      if (code !== 0) {
        reject(
          new Error(
            `ffmpeg failed while extracting waveform from ${filePath}: ${Buffer.concat(stderr).toString("utf8")}`,
          ),
        );
        return;
      }

      resolve(Buffer.concat(chunks));
    });
  });

  const floatCount = Math.floor(pcm.length / 4);
  if (floatCount === 0) {
    return Array.from({ length: sampleCount }, () => 0);
  }

  const amplitudes = Array.from({ length: floatCount }, (_value, index) => {
    return Math.abs(pcm.readFloatLE(index * 4));
  });

  const samplesPerBucket = Math.max(1, Math.floor(amplitudes.length / sampleCount));

  return Array.from({ length: sampleCount }, (_value, index) => {
    const start = index * samplesPerBucket;
    const end = index === sampleCount - 1 ? amplitudes.length : Math.min(amplitudes.length, start + samplesPerBucket);
    if (start >= amplitudes.length) {
      return 0;
    }

    let sumSquares = 0;
    for (let cursor = start; cursor < end; cursor += 1) {
      sumSquares += amplitudes[cursor] * amplitudes[cursor];
    }

    return Math.sqrt(sumSquares / Math.max(1, end - start));
  });
}

async function buildWaveform(filePaths: string[], durationsMs: number[]): Promise<number[]> {
  if (filePaths.length === 0) {
    return Array.from({ length: WAVEFORM_BAR_COUNT }, () => 0.12);
  }

  const barsPerSegment = allocateWaveformBars(durationsMs, WAVEFORM_BAR_COUNT);
  const segmentSamples = await Promise.all(
    filePaths.map((filePath, index) => extractWaveformSamples(filePath, barsPerSegment[index] ?? 0)),
  );

  const merged = segmentSamples.flat().slice(0, WAVEFORM_BAR_COUNT);
  while (merged.length < WAVEFORM_BAR_COUNT) {
    merged.push(0);
  }

  const max = merged.reduce((currentMax, value) => Math.max(currentMax, value), 0);
  if (max === 0) {
    return merged.map(() => 0.12);
  }

  return merged.map((value) => {
    const normalized = value / max;
    return Number((0.12 + normalized * 0.88).toFixed(4));
  });
}

async function localizeSegments(segments: SegmentMetadata[]): Promise<{
  localizedSegments: SegmentMetadata[];
  localFilePaths: string[];
  cleanup: () => Promise<void>;
}> {
  if (segments.length === 0) {
    return {
      localizedSegments: segments,
      localFilePaths: [],
      cleanup: () => Promise.resolve(),
    };
  }

  const assetDir = await mkdtemp(path.join(tmpdir(), "remotion-audio-"));
  const registeredAssetIds: string[] = [];

  try {
    const localFilePaths: string[] = [];
    const localizedSegments = await Promise.all(
      segments.map(async (segment, index) => {
        console.log("Downloading segment asset", {
          index,
          speaker: segment.speaker,
          source: segment.url,
        });

        const response = await fetch(segment.url);
        if (!response.ok || !response.body) {
          throw new Error(
            `Failed to download segment ${index} from source URL: HTTP ${response.status}`,
          );
        }

        const contentType = response.headers.get("content-type") ?? "application/octet-stream";
        const filePath = path.join(
          assetDir,
          `${String(index).padStart(2, "0")}-${randomUUID()}${getAssetExtension(
            segment.url,
            contentType,
          )}`,
        );

        await pipeline(
          Readable.fromWeb(response.body as unknown as NodeReadableStream),
          createWriteStream(filePath),
        );
        await access(filePath);
        await probeAudio(filePath);
        localFilePaths[index] = filePath;

        const assetId = randomUUID();
        registeredAssetIds.push(assetId);
        localAssetRegistry.set(assetId, { filePath, contentType });

        console.log("Segment asset ready", {
          index,
          speaker: segment.speaker,
          contentType,
          localAssetId: assetId,
        });

        return {
          ...segment,
          url: `http://127.0.0.1:${PORT}/render-assets/${assetId}`,
        };
      }),
    );

    return {
      localizedSegments,
      localFilePaths,
      cleanup: async () => {
        registeredAssetIds.forEach((assetId) => localAssetRegistry.delete(assetId));
        await rm(assetDir, { recursive: true, force: true });
      },
    };
  } catch (error) {
    registeredAssetIds.forEach((assetId) => localAssetRegistry.delete(assetId));
    await rm(assetDir, { recursive: true, force: true });
    throw error;
  }
}

function normalizeSegments(input: unknown): SegmentMetadata[] {
  if (input === undefined) return [];
  if (!Array.isArray(input)) {
    throw new Error("`props.segments` must be an array.");
  }

  return input.map((segment, index) => {
    if (typeof segment !== "object" || segment === null) {
      throw new Error(`Segment at index ${index} must be an object.`);
    }

    const candidate = segment as Partial<SegmentMetadata>;
    const speaker = typeof candidate.speaker === "string" ? candidate.speaker.trim() : "";
    const url = typeof candidate.url === "string" ? candidate.url.trim() : "";
    const durationMs = Number(candidate.durationMs);

    if (!url) {
      throw new Error(`Segment at index ${index} is missing a valid \`url\`.`);
    }

    if (!Number.isFinite(durationMs) || durationMs <= 0) {
      throw new Error(`Segment at index ${index} must include a positive \`durationMs\`.`);
    }

    return {
      speaker: speaker || `segment-${index + 1}`,
      url,
      durationMs,
      color: typeof candidate.color === "string" ? candidate.color : undefined,
    };
  });
}

function getRawProps(input: unknown): Record<string, unknown> {
  return typeof input === "object" && input !== null ? (input as Record<string, unknown>) : {};
}

function getRenderComposition(input: unknown): string {
  const body = getRawProps(input);
  return String(body.composition ?? REMOTION_COMPOSITION_ID);
}

function validateRenderSegments(composition: string, rawProps: Record<string, unknown>): SegmentMetadata[] {
  const normalizedSegments = normalizeSegments(rawProps.segments);

  if (composition === REMOTION_COMPOSITION_ID && normalizedSegments.length === 0) {
    throw new Error("`props.segments` must be a non-empty array for DarkFactoryScene.");
  }

  return normalizedSegments;
}

function isRenderValidationError(detail: string): boolean {
  return detail.includes("`props.segments`") || detail.includes("Segment at index");
}

type ClipManifestClip = {
  id: string;
  start: number; // seconds
  end: number; // seconds
  title: string;
  authorHandle?: string;
  avatarUrl?: string;
  captions?: {
    start: number;
    end: number;
    text: string;
  }[];
};

type ClipManifest = {
  video: string;
  clips: ClipManifestClip[];
  brandId?: string;
  authorHandle?: string;
  avatarUrl?: string;
  // Optional local path to a Whisper-style transcript JSON with a `segments` array.
  // If provided and an individual clip does not define explicit captions, the
  // server will derive caption cues for that clip by slicing the transcript
  // between the clip's start/end times.
  transcriptPath?: string;
    // Optional S3 key for the source video; if provided, the server
    // will download the object directly from S3 instead of expecting
    // an externally reachable HTTP URL.
    videoKey?: string;
};

async function resolveVideoUrl(raw: string): Promise<string> {
  const value = raw.trim();
  if (!value) {
    throw new Error("Manifest is missing a non-empty video field.");
  }

  if (value.startsWith("http://") || value.startsWith("https://")) {
    return value;
  }

  const filePath = value.startsWith("file://") ? value.replace(/^file:\/\//, "") : value;

  const assetId = randomUUID();
  localAssetRegistry.set(assetId, {
    filePath,
    contentType: "video/mp4",
  });

  return `http://127.0.0.1:${PORT}/render-assets/${assetId}`;
}

async function localizeVideoSource(options: {
  video?: string;
  videoKey?: string;
}): Promise<{
  url: string;
  cleanup: () => Promise<void>;
}> {
  const { video, videoKey } = options;

  // 1) Prefer explicit S3 key if provided
  if (videoKey) {
    if (!bucketName || !s3Client) {
      throw new Error("Cannot use videoKey without S3 bucket configuration.");
    }

    const tmpFile = path.join(tmpdir(), `remotion-video-${randomUUID()}.mp4`);

    console.log("Downloading source video from S3", {
      bucket: bucketName,
      key: videoKey,
      tmpFile,
    });

    const object = await s3Client.send(
      new GetObjectCommand({
        Bucket: bucketName,
        Key: videoKey,
      }),
    );

    if (!object.Body) {
      throw new Error("S3 GetObject returned an empty body for videoKey.");
    }

    await pipeline(
      object.Body as unknown as Readable,
      createWriteStream(tmpFile),
    );

    const assetId = randomUUID();
    localAssetRegistry.set(assetId, {
      filePath: tmpFile,
      contentType: "video/mp4",
    });

    return {
      url: `http://127.0.0.1:${PORT}/render-assets/${assetId}`,
      cleanup: async () => {
        localAssetRegistry.delete(assetId);
        await rm(tmpFile, { force: true });
      },
    };
  }

  // 2) If we have a HTTP(S) URL, download it once and serve locally
  if (video && (video.startsWith("http://") || video.startsWith("https://"))) {
    const tmpFile = path.join(tmpdir(), `remotion-video-${randomUUID()}.mp4`);

    console.log("Downloading source video from URL", {
      src: video,
      tmpFile,
    });

    const response = await fetch(video);
    if (!response.ok || !response.body) {
      throw new Error(`Failed to download source video from ${video}: HTTP ${response.status}`);
    }

    await pipeline(
      Readable.fromWeb(response.body as unknown as NodeReadableStream),
      createWriteStream(tmpFile),
    );

    const assetId = randomUUID();
    localAssetRegistry.set(assetId, {
      filePath: tmpFile,
      contentType: "video/mp4",
    });

    return {
      url: `http://127.0.0.1:${PORT}/render-assets/${assetId}`,
      cleanup: async () => {
        localAssetRegistry.delete(assetId);
        await rm(tmpFile, { force: true });
      },
    };
  }

  // 3) Fallback: Local file path (for development)
  if (video) {
    const filePath = video.startsWith("file://") ? video.replace(/^file:\/\//, "") : video;
    console.log("Using local video file", { filePath });

    const assetId = randomUUID();
    localAssetRegistry.set(assetId, {
      filePath,
      contentType: "video/mp4",
    });

    return {
      url: `http://127.0.0.1:${PORT}/render-assets/${assetId}`,
      cleanup: async () => {
        localAssetRegistry.delete(assetId);
      },
    };
  }

  throw new Error("Either video or videoKey must be provided in the manifest.");
}

app.get("/healthz", (_req, res) => {
  res.sendStatus(200);
});

app.get("/render-assets/:assetId", (req, res) => {
  const asset = localAssetRegistry.get(req.params.assetId);
  if (!asset) {
    console.warn("render-assets: missing asset", { assetId: req.params.assetId });
    res.sendStatus(404);
    return;
  }

  console.log("render-assets: serving asset", {
    assetId: req.params.assetId,
    filePath: asset.filePath,
    contentType: asset.contentType,
  });

  res.setHeader("Content-Type", asset.contentType);
  createReadStream(asset.filePath).pipe(res);
});

app.get(/^\/render-outputs\/(.+)$/, async (req, res) => {
  const rawKey = String(req.params[0] ?? "");
  const key = rawKey.replace(/^\/+/, "");

  if (!key || !isAllowedOutputKey(key)) {
    res.sendStatus(404);
    return;
  }

  try {
    if (!bucketName) {
      if (!localOutputDir) {
        res.sendStatus(404);
        return;
      }

      const baseDir = path.resolve(localOutputDir);
      const filePath = path.resolve(baseDir, key);
      if (!filePath.startsWith(`${baseDir}${path.sep}`) && filePath !== baseDir) {
        res.sendStatus(404);
        return;
      }

      res.setHeader("Content-Type", "video/mp4");
      createReadStream(filePath).on("error", () => res.sendStatus(404)).pipe(res);
      return;
    }

    if (!s3Client) {
      res.sendStatus(404);
      return;
    }

    const object = await s3Client.send(
      new GetObjectCommand({
        Bucket: bucketName,
        Key: key,
      }),
    );

    res.setHeader("Content-Type", object.ContentType ?? "video/mp4");
    if (object.ContentLength !== undefined) {
      res.setHeader("Content-Length", String(object.ContentLength));
    }

    (object.Body as unknown as Readable).pipe(res);
  } catch (error) {
    console.error("render-outputs failed", { key, error });
    if (!res.headersSent) {
      res.sendStatus(404);
    } else {
      res.end();
    }
  }
});

app.get("/compositions", async (_req, res) => {
  try {
    const serveUrl = await ensureBundle();
    const comps = await getCompositions(serveUrl);
    res.json(
      comps.map((comp) => ({
        id: comp.id,
        durationInFrames: comp.durationInFrames,
        fps: comp.fps,
        width: comp.width,
        height: comp.height,
        schemaUrl: `/compositions/${comp.id}/schema`,
      })),
    );
  } catch (error) {
    console.error("Failed to list compositions", error);
    res.status(500).json({ error: "Unable to list compositions" });
  }
});

app.get("/compositions/:compositionId/schema", (req, res) => {
  const schema = compositionSchemas[req.params.compositionId as keyof typeof compositionSchemas];

  if (!schema) {
    res.status(404).json({ error: "Composition schema not found." });
    return;
  }

  res.json(schema);
});

app.get("/schemas", (_req, res) => {
  res.json(compositionSchemas);
});

// Asynchronous variant of long-form /render. Returns quickly with a
// job ID and lets the actual render work happen in the background.

app.post("/render-async", (req, res) => {
  const body = (req.body ?? {}) as unknown;

  if (!body || typeof body !== "object") {
    res.status(400).json({ error: "Body must be a JSON object." });
    return;
  }

  try {
    const composition = getRenderComposition(body);
    const rawProps = getRawProps((body as Record<string, unknown>).props);
    validateRenderSegments(composition, rawProps);
  } catch (error) {
    res.status(400).json({
      error: "Invalid render input",
      detail: (error as Error)?.message ?? "Unknown validation error",
    });
    return;
  }

  const job = createRenderJob(body);
  void runRenderJob(job.id, body);

  res.status(202).json({
    jobId: job.id,
    status: job.status,
    createdAt: job.createdAt,
    inputSummary: job.inputSummary,
  });
});

app.get("/render-async/:jobId", (req, res) => {
  const job = renderJobs.get(req.params.jobId);
  if (!job) {
    res.status(404).json({ error: "Job not found" });
    return;
  }

  res.json(job);
});

// Asynchronous variant of /render-clips that returns quickly with a
// job ID while the actual rendering work happens in the background.
// Useful for environments like Railway where long-lived HTTP
// connections are likely to be terminated by the proxy.

app.post("/render-clips-async", (req, res) => {
  const body = (req.body ?? {}) as Partial<ClipManifest>;

  if (!body || typeof body !== "object") {
    res.status(400).json({ error: "Body must be a JSON object." });
    return;
  }

  if (!Array.isArray(body.clips) || body.clips.length === 0) {
    res.status(400).json({ error: "`clips` must be a non-empty array." });
    return;
  }

  if (typeof body.video !== "string" && typeof body.videoKey !== "string") {
    res.status(400).json({
      error: "Either `video` (URL or path) or `videoKey` (S3 key) must be provided.",
    });
    return;
  }

  const job = createClipRenderJob(body);
  void runClipRenderJob(job.id, body);

  res.status(202).json({
    jobId: job.id,
    status: job.status,
    createdAt: job.createdAt,
    inputSummary: job.inputSummary,
  });
});

app.get("/render-clips-async/:jobId", (req, res) => {
  const job = clipRenderJobs.get(req.params.jobId);
  if (!job) {
    res.status(404).json({ error: "Job not found" });
    return;
  }

  res.json(job);
});

app.post("/render-clips", async (req, res) => {
  const body = (req.body ?? {}) as Partial<ClipManifest>;
  let cleanupVideo: (() => Promise<void>) | null = null;

  try {
    if (!body || typeof body !== "object") {
      throw new Error("Body must be a JSON object.");
    }

    if (!Array.isArray(body.clips) || body.clips.length === 0) {
      throw new Error("`clips` must be a non-empty array.");
    }

    if (typeof body.video !== "string" && typeof body.videoKey !== "string") {
      throw new Error("Either `video` (URL or path) or `videoKey` (S3 key) must be provided.");
    }

    // Optionally load a transcript JSON from disk that contains a `segments`
    // array with `{ start, end, text }` entries. We'll slice this per-clip to
    // derive relative caption cues when a clip doesn't specify captions
    // explicitly.
    type TranscriptSegment = { start: number; end: number; text: string };
    let transcriptSegments: TranscriptSegment[] | null = null;

    if (typeof body.transcriptPath === "string" && body.transcriptPath.trim() !== "") {
      const transcriptPath = body.transcriptPath.trim();
      try {
        const raw = await readFile(transcriptPath, { encoding: "utf8" });
        const parsed = JSON.parse(raw) as { segments?: unknown };
        if (!Array.isArray(parsed.segments)) {
          throw new Error("Transcript JSON is missing a segments array.");
        }

        transcriptSegments = (parsed.segments as unknown[])
          .map((segment) => {
            if (typeof segment !== "object" || segment === null) return null;
            const candidate = segment as { start?: unknown; end?: unknown; text?: unknown };
            const start = Number(candidate.start);
            const end = Number(candidate.end);
            const text = typeof candidate.text === "string" ? candidate.text.trim() : "";
            if (!Number.isFinite(start) || !Number.isFinite(end) || !text) return null;
            return { start, end, text } satisfies TranscriptSegment;
          })
          .filter((segment): segment is TranscriptSegment => segment !== null);

        console.log("Loaded transcript for render-clips", {
          transcriptPath,
          segmentCount: transcriptSegments.length,
        });
      } catch (error) {
        console.error("Failed to load transcriptPath for render-clips", {
          transcriptPath: body.transcriptPath,
          error,
        });
        throw new Error("Unable to read transcriptPath JSON. See server logs for details.");
      }
    }

    const localizedVideo = await localizeVideoSource({
      video: typeof body.video === "string" ? body.video : undefined,
      videoKey: typeof body.videoKey === "string" ? body.videoKey : undefined,
    });
    cleanupVideo = localizedVideo.cleanup;
    const videoUrl = localizedVideo.url;
    const brandId = typeof body.brandId === "string" ? body.brandId : undefined;
    const manifestAuthorHandle = typeof body.authorHandle === "string" ? body.authorHandle : undefined;
    const manifestAvatarUrl = typeof body.avatarUrl === "string" ? body.avatarUrl : undefined;

    const serveUrl = await ensureBundle();

    const results: Array<{
      id: string;
      bucket: string | null;
      key: string;
      endpoint?: string | undefined;
      location: string;
      url?: string | undefined;
      proxyUrl?: string | undefined;
    }> = [];

    for (const clip of body.clips) {
      if (!clip || typeof clip !== "object") {
        throw new Error("Every clip must be an object.");
      }

      const { id, start, end, title } = clip;
      if (!id || typeof id !== "string") {
        throw new Error("Each clip must have an `id` string.");
      }
      if (typeof start !== "number" || typeof end !== "number" || !Number.isFinite(start) || !Number.isFinite(end) || end <= start) {
        throw new Error(`Clip ${id} must have numeric start/end seconds with end > start.`);
      }
      if (!title || typeof title !== "string") {
        throw new Error(`Clip ${id} must have a non-empty title.`);
      }

      let captions = Array.isArray(clip.captions)
        ? clip.captions
            .filter((cue) =>
              cue && typeof cue.start === "number" && typeof cue.end === "number" && typeof cue.text === "string",
            )
            .map((cue) => ({
              start: cue.start,
              end: cue.end,
              text: cue.text,
            }))
        : [];

      // If no explicit captions are provided but we have a transcript
      // loaded, derive clip-relative caption cues by slicing the global
      // transcript between the clip's absolute start/end times.
      if (captions.length === 0 && transcriptSegments && transcriptSegments.length > 0) {
        const clipDuration = end - start;
        const MIN_AUTO_CAPTION_DURATION = 0.5; // seconds

        const cues = transcriptSegments
          .map((segment) => {
            const segStart = segment.start;
            const segEnd = segment.end;
            if (!Number.isFinite(segStart) || !Number.isFinite(segEnd)) return null;
            if (segEnd <= start || segStart >= end) return null;

            const relativeStart = Math.max(0, segStart - start);
            const relativeEnd = Math.min(clipDuration, segEnd - start);
            if (relativeEnd <= relativeStart) return null;

            return {
              start: Number(relativeStart.toFixed(2)),
              end: Number(relativeEnd.toFixed(2)),
              text: segment.text,
            };
          })
          .filter((cue): cue is { start: number; end: number; text: string } => cue !== null);

        const filtered = cues.filter((cue) => cue.end - cue.start >= MIN_AUTO_CAPTION_DURATION);
        captions = filtered;
        console.log("Derived captions from transcript for clip", {
          id,
          clipDuration,
          captionCount: captions.length,
        });
      }

      const props = {
        videoUrl,
        title,
        clipId: id,
        brandId,
        authorHandle: typeof clip.authorHandle === "string" ? clip.authorHandle : manifestAuthorHandle,
        avatarUrl: typeof clip.avatarUrl === "string" ? clip.avatarUrl : manifestAvatarUrl,
        startSeconds: start,
        endSeconds: end,
        captions,
      } satisfies Record<string, unknown>;

      const outputKey = composeKey(`${id}-${Date.now()}`, REMOTION_SHORT_COMPOSITION_ID);
      const tmpFile = path.join(tmpdir(), `remotion-clip-${id}-${randomUUID()}.mp4`);

      console.log("Short clip render requested", {
        composition: REMOTION_SHORT_COMPOSITION_ID,
        clipId: id,
        title,
        start,
        end,
        outputKey,
      });

      const videoConfig = await selectComposition({
        serveUrl,
        id: REMOTION_SHORT_COMPOSITION_ID,
        inputProps: props,
      });

      await renderMedia({
        serveUrl,
        composition: videoConfig,
        outputLocation: tmpFile,
        inputProps: props,
        codec: "h264",
        enforceAudioTrack: true,
        jpegQuality: 90,
        logLevel: "verbose",
        timeoutInMilliseconds: 120000,
        concurrency: 1,
        onBrowserLog: ({ text, type }) => {
          console.log("ShortClip browser log", { type, text });
        },
      });

      const upload = await uploadToS3(tmpFile, outputKey);
      console.log("Short clip upload complete", {
        clipId: id,
        bucket: upload.bucket ?? bucketName,
        key: upload.key,
        location: upload.location,
      });

      results.push({
        id,
        bucket: upload.bucket ?? bucketName ?? null,
        key: upload.key,
        endpoint,
        location: upload.location,
        url: upload.url,
        proxyUrl: upload.proxyUrl,
      });
    }

    res.status(201).json({
      video: body.video,
      clips: results,
    });
  } catch (error) {
    const detail = (error as Error)?.message ?? "Unknown clip render error";
    console.error("render-clips failed", error);
    res.status(400).json({
      error: "Invalid clip render input",
      detail,
    });
  } finally {
    if (cleanupVideo) {
      try {
        await cleanupVideo();
      } catch (error) {
        console.error("Video cleanup after render-clips failed", error);
      }
    }
  }
});

async function renderScene(body: unknown): Promise<RenderJobResult> {
  const requestBody = getRawProps(body);
  const composition = getRenderComposition(requestBody);
  const requestedKey =
    typeof requestBody.outputKey === "string" ? requestBody.outputKey.trim() : undefined;
  const outputKey = composeKey(requestedKey, composition);
  const tmpFile = path.join(tmpdir(), `remotion-${randomUUID()}.mp4`);
  let cleanupLocalizedSegments: (() => Promise<void>) | null = null;

  try {
    const rawProps = getRawProps(requestBody.props);
    const normalizedSegments = validateRenderSegments(composition, rawProps);
    const { localizedSegments, localFilePaths, cleanup } = await localizeSegments(normalizedSegments);
    cleanupLocalizedSegments = cleanup;
    const measuredDurationsMs = await Promise.all(
      localFilePaths.map(async (filePath, index) => {
        try {
          return await probeAudioDurationMs(filePath);
        } catch (error) {
          console.warn("Unable to probe localized segment duration", {
            index,
            filePath,
            error,
          });
          return normalizedSegments[index]?.durationMs ?? localizedSegments[index]?.durationMs ?? 0;
        }
      }),
    );
    const segmentsWithResolvedDurations = localizedSegments.map((segment, index) => {
      const providedDurationMs = normalizedSegments[index]?.durationMs ?? segment.durationMs;
      const measuredDurationMs = measuredDurationsMs[index];
      const resolvedDurationMs = Math.max(
        segment.durationMs,
        providedDurationMs,
        Number.isFinite(measuredDurationMs)
          ? measuredDurationMs + AUDIO_DURATION_TAIL_PADDING_MS
          : 0,
      );

      return {
        ...segment,
        durationMs: resolvedDurationMs,
      };
    });
    const waveform = await buildWaveform(
      localFilePaths,
      segmentsWithResolvedDurations.map((segment) => segment.durationMs),
    );
    const props: SceneProps & Record<string, unknown> = {
      ...rawProps,
      segments: segmentsWithResolvedDurations,
      waveform,
    };
    console.log("Render requested", {
      composition,
      propsPreview: {
        title: props?.title,
        segments: Array.isArray(props?.segments) ? props.segments.length : undefined,
        waveformBars: props.waveform?.length,
        requestedDurationMs: normalizedSegments.reduce(
          (total, segment) => total + segment.durationMs,
          0,
        ),
        resolvedDurationMs: segmentsWithResolvedDurations.reduce(
          (total, segment) => total + segment.durationMs,
          0,
        ),
      },
      outputKey,
    });
    const serveUrl = await ensureBundle();
    const videoConfig = await selectComposition({
      serveUrl,
      id: composition,
      inputProps: props,
      onBrowserDownload: ({ chromeMode }) => {
        console.log("Ensuring Chromium is available", { chromeMode });
        return {
          version: null,
          onProgress: () => undefined,
        };
      },
    });
    console.log("renderMedia start", { composition, outputLocation: tmpFile });
    await renderMedia({
      serveUrl,
      composition: videoConfig,
      outputLocation: tmpFile,
      inputProps: props,
      codec: "h264",
      enforceAudioTrack: true,
      jpegQuality: 90,
      logLevel: "error",
      concurrency: 1,
      timeoutInMilliseconds: 120000,
      onDownload: (src) => {
        console.log("Renderer downloading media", { src });
        return ({ percent, downloaded, totalSize }) => {
          if (percent === 1 || (totalSize !== null && downloaded >= totalSize)) {
            console.log("Renderer media download complete", { src, downloaded, totalSize });
          }
        };
      },
      onBrowserLog: ({ text, type }) => {
        if (type === "warning" || type === "error") {
          console.warn("Browser log", { type, text });
        }
      },
    });
    console.log("renderMedia complete", { composition, outputLocation: tmpFile });

    const upload = await uploadToS3(tmpFile, outputKey);
    console.log("uploadToS3 complete", {
      bucket: upload.bucket ?? bucketName,
      key: upload.key,
      location: upload.location,
      url: upload.url,
      proxyUrl: upload.proxyUrl,
    });

    const result = {
      bucket: upload.bucket ?? bucketName ?? null,
      key: upload.key,
      endpoint,
      location: upload.location,
      url: upload.url,
      proxyUrl: upload.proxyUrl,
    } satisfies RenderJobResult;

    console.log("Render result ready", result);
    return result;
  } finally {
    try {
      await cleanupRenderArtifacts({
        cleanupLocalizedSegments,
        tmpFile,
      });
      console.log("Render cleanup complete", { outputKey });
    } catch (error) {
      console.error("Render cleanup failed", error);
    }
  }
}

app.post("/render", async (req, res) => {
  try {
    const result = await renderScene(req.body);
    console.log("Sending render response", result);
    res.status(201).json(result);
  } catch (error) {
    const detail = (error as Error)?.message ?? "Unknown render error";
    const isValidationError = isRenderValidationError(detail);
    console.error("Render failed", error);
    res.status(isValidationError ? 400 : 500).json({
      error: isValidationError ? "Invalid render input" : "Render failed",
      detail,
    });
  }
});

app.listen(PORT, () => {
  console.log(`Remotion service listening on port ${PORT}`);
});
